baseURL: /
theme: hugo-apero
languageCode: en
title: Personal website
author: Radosław Pańczak
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: Personal website of Radosław Pańczak.
  favicon: /img/globe-europe-solid.ico
  headingFontFamily: sans-serif
  logo: /img/globe-europe-solid.svg
  mainSections:
    - project
    # - blog
    # - talk
  navallcaps: yes
  orgLocal: 
  orgName: Radosław Pańczak
  sharing_image: /img/papillons.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/RPanczak
    - icon: orcid
      icon_pack: ai
      url: http://orcid.org/0000-0001-5141-683X
    - icon: google-scholar
      icon_pack: ai
      url: https://scholar.google.com/citations?user=8j-L0asAAAAJ
    - icon: osf
      icon_pack: ai
      url: https://osf.io/2xk8n/
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/RPanczak
    # - icon: rss
    #   icon_pack: fas
    #   url: /blog/index.xml
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: grayscale
  twitter: RPanczak
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: apreshill/apero
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 2
    # - name: Contributors
    #   title: Contributors
    #   url: /contributors/
    #   weight: 3
  header:
    - name: About
      title: About me
      url: /about/
      weight: 1
    # - name: Blog
    #   title: Blog
    #   url: /blog/
    #   weight: 3
    - name: Projects
      title: Project Portfolio
      url: /project/
      weight: 2
    # - name: Talks
    #   title: Talks
    #   url: /talk/
    #   weight: 4
    # - name: A collection
    #   title: A collection
    #   url: /collection/
    #   weight: 5
privacy:
  disqus:
    disable: yes
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: yes
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: yes
    enableDNT: yes
    simple: yes
  youtube:
    disable: yes
    privacyEnhanced: yes
